### PR TITLE
A round of review

### PR DESCRIPTION
**Pull request by stucchimax**
I've looked at the document and attempted to make it more readable.  I'm not a native speaker, but I think a fresh reader can help in improving the writing.

### CODE REVIEW

**Review by maelmans — APPROVED** [review]
Better. Thanks!

**Review by maelmans — CHANGES_REQUESTED** [review]
Can you change the wording of "These information are". Then I think it's better.

**Comment by maelmans** [comment]
Great work and thanks for reviewing the document Massimiliano!

**Comment by BarryRGreene** [comment]
Suggest a new section:

Start First with the BGP BCPs!

RPKI assumes that the organization has deployed their BGP ingress/egress essentials, that they have taken the time to write down their BGP policy, and they are following the practices with all the BGP peers (transit, peering, IXPs, and customers). It would be foolish to jump into RPKI without covering the basics. Much of the BGP security and resiliency risk is reduced just through diligent BGP BCP deployment.

**Comment by AlexanderBand** [comment]
> Suggest a new section:
> 
> Start First with the BGP BCPs!

While I agree that it is a good idea to add this, I think it goes beyond of what you would put in a FAQ. Looking at how well this FAQ is evolving, we may want to just start documentation pages in a similar fashion (e.g. Github + Sphinx + Readthedocs.io).

**Comment by maelmans** [comment]
> > Start First with the BGP BCPs!
> 
> While I agree that it is a good idea to add this, I think it goes beyond of what you would put in a FAQ. Looking at how well this FAQ is evolving, we may want to just start documentation pages in a similar fashion (e.g. Github + Sphinx + Readthedocs.io).

I agree with Alex that this isn't in scope for a FAQ. We could however link to the NLNOG BCP however.

**Review by maelmans — APPROVED** [review]

**Pull request merged**
